/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'publishedAt' : bigint,
  'author' : string,
  'excerpt' : string,
}
export interface Lead {
  'id' : bigint,
  'orgType' : string,
  'name' : string,
  'createdAt' : bigint,
  'message' : string,
  'phone' : string,
}
export type LeadResult = { 'ok' : bigint } |
  { 'err' : string };
export type PostResult = { 'ok' : bigint } |
  { 'err' : string };
export interface Testimonial {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'quote' : string,
  'isVisible' : boolean,
  'organization' : string,
}
export type TestimonialResult = { 'ok' : bigint } |
  { 'err' : string };
export type UpdateResult = { 'ok' : null } |
  { 'err' : string };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<
    [string, string, string, string, string, boolean],
    PostResult
  >,
  'createTestimonial' : ActorMethod<
    [string, string, string, string, boolean],
    TestimonialResult
  >,
  'deletePost' : ActorMethod<[bigint], UpdateResult>,
  'deleteTestimonial' : ActorMethod<[bigint], UpdateResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getPublishedPosts' : ActorMethod<[], Array<BlogPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisibleTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLead' : ActorMethod<[string, string, string, string], LeadResult>,
  'updatePost' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    UpdateResult
  >,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    UpdateResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];